---

- name: Set managed uninstalls
  set_fact:
        macos_munki_localonlymanifest__managed_uninstalls_list:
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adium | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_teamviewer | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeacrobatpro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeaftereffects | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeanimate | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeaudition | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobebridge | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobecharacteranimator | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobedreamweaver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobefireworks | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeflashbuilder | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeflashplayer | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobefuse | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobegamingsdk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeillustrator | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeincopy | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeindesign | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobelightroom | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobemediaencoder | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobemuse | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobephotoshop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobeprelude | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobepremierepro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobescout | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_adobespeedgrade | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_atom | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_audacity | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_autopkg | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_bibdesk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_canonpsprinterdriver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_ciscoanyconnect | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_ciscojabber | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_citrixreceiver | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_crashplan | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_createuserpkg | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_cyberduck | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_endnote | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_evernote | default('')}}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_f5transkript | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_facter | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_fiji | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_filemakerpro | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_flux | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_freemind | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_garageband | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_geneious | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_gimp | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_googlechrome | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_googleearth | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_hewlettpackardprinterdrivers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_imovie | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_inkscape | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_iterm2 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_karabiner | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_keynote | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_latexit | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_libreoffice | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_mactex | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_mactracker | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_mathematica | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_matlab | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_maxqda | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_mendeleydesktop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_microsoftremotedesktop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_msexcel2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_msonenote2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_msoutlook2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_mspowerpoint2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_msword2016 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_nomad | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_numbers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_omeroinsight | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_oraclejava8jdk | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_oraclejava8jre | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other01 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other02 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other03 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other04 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other05 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other06 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other07 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other08 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other09 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_other10 | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_pages | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_papers | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_prism | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_processing | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_r | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_rstudio | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_silverlight | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_skype | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_slack | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_spotify | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_spss | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_suspiciouspackage | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_switchdrive | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_symantecendpointprotection | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_texshop | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_vienna | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_virtualbox | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_vlc | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_xquartz | default('') }}"
                - "{{ macos_munki_localonlymanifest__managed_uninstalls_zotero | default('') }}"

- name: Clean up list
  set_fact:
        macos_munki_localonlymanifest__managed_uninstalls_list: "{{ macos_munki_localonlymanifest__managed_uninstalls_list | unique | difference('') }}"
